#!/usr/bin/env python
#
#  Copyright (c) 2013, Sean Reifschneider, tummy.com, ltd.
#  All Rights Reserved.

import sys
import os
import model
import bottle
import website

if __name__.startswith('_mod_wsgi_'):
    os.chdir(os.path.dirname(__file__))
    sys.path.append('lib')
    sys.path.append('.')

    application = website.web_interface()

if __name__ == '__main__':
    sys.path.append('lib')
    sys.path.append('tests')

    if os.environ.get('GATEWAY_INTERFACE'):
        #  Called from CGI
        app = website.web_interface()
        bottle.run(app, server=bottle.CGIServer)
        sys.exit(0)

    if 'test-server' in sys.argv[1:]:
        sys.path.append('tests')

        if os.environ.get('DBCREDENTIALSTR') == 'sqlite:///:memory:':
            model.initdb()
        app = website.web_interface()
        bottle.run(app, reloader=True, host='127.0.0.1', port=8080)
        sys.exit(0)

    if 'initdb' in sys.argv[1:]:
        'Run database initialization'
        model.initdb()
        sys.exit(0)

    if 'load-test-data' in sys.argv[1:]:
        'Load test data-set'
        model.create_sample_data()
        sys.exit(0)
