#!/usr/bin/env python
#
#  This is about the simplest Bottle app you can make.
#
#  See the README.md for more information
#
#  Written by Sean Reifschneider <jafo@jafo.ca>, 2013
#
#  Part of the python-bottle-skeleton project at:
#
#      https://github.com/linsomniac/python-bottle-skeleton
#
#  I hereby place this work, python-bottle-wrapper, into the public domain.

import bottle

def website():
    app = bottle.Bottle()

    bottle.TEMPLATE_PATH.insert(0, 'views')

    @app.route('/', name='index')    #  XXX Location of page
    @bottle.view('index')            #  XXX Template to use
    def index():
        #  XXX Page code here

        import datetime

        now = datetime.datetime.now()

        #  XXX Return variables for use in page rendering
        return {'now': now, 'app': app}

    return app

app = website()
bottle.debug(True)
bottle.run(app, reloader=True, host='127.0.0.1', port=8080)
